/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrafficLightIdRouteImport } from './routes/traffic-light.$id'
import { Route as ApiPublicDevicesHeartbeatRouteImport } from './routes/api/public/devices/heartbeat'
import { Route as ApiPublicDevicesDetectionRouteImport } from './routes/api/public/devices/detection'
import { Route as ApiPublicDevicesSignalIdRouteImport } from './routes/api/public/devices/signal.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficLightIdRoute = TrafficLightIdRouteImport.update({
  id: '/traffic-light/$id',
  path: '/traffic-light/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDevicesHeartbeatRoute =
  ApiPublicDevicesHeartbeatRouteImport.update({
    id: '/api/public/devices/heartbeat',
    path: '/api/public/devices/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevicesDetectionRoute =
  ApiPublicDevicesDetectionRouteImport.update({
    id: '/api/public/devices/detection',
    path: '/api/public/devices/detection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDevicesSignalIdRoute =
  ApiPublicDevicesSignalIdRouteImport.update({
    id: '/api/public/devices/signal/$id',
    path: '/api/public/devices/signal/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/logs': typeof LogsRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/traffic-light/$id': typeof TrafficLightIdRoute
  '/api/public/devices/detection': typeof ApiPublicDevicesDetectionRoute
  '/api/public/devices/heartbeat': typeof ApiPublicDevicesHeartbeatRoute
  '/api/public/devices/signal/$id': typeof ApiPublicDevicesSignalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/logs': typeof LogsRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/traffic-light/$id': typeof TrafficLightIdRoute
  '/api/public/devices/detection': typeof ApiPublicDevicesDetectionRoute
  '/api/public/devices/heartbeat': typeof ApiPublicDevicesHeartbeatRoute
  '/api/public/devices/signal/$id': typeof ApiPublicDevicesSignalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/logs': typeof LogsRoute
  '/recordings': typeof RecordingsRoute
  '/settings': typeof SettingsRoute
  '/traffic-light/$id': typeof TrafficLightIdRoute
  '/api/public/devices/detection': typeof ApiPublicDevicesDetectionRoute
  '/api/public/devices/heartbeat': typeof ApiPublicDevicesHeartbeatRoute
  '/api/public/devices/signal/$id': typeof ApiPublicDevicesSignalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/logs'
    | '/recordings'
    | '/settings'
    | '/traffic-light/$id'
    | '/api/public/devices/detection'
    | '/api/public/devices/heartbeat'
    | '/api/public/devices/signal/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/logs'
    | '/recordings'
    | '/settings'
    | '/traffic-light/$id'
    | '/api/public/devices/detection'
    | '/api/public/devices/heartbeat'
    | '/api/public/devices/signal/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/logs'
    | '/recordings'
    | '/settings'
    | '/traffic-light/$id'
    | '/api/public/devices/detection'
    | '/api/public/devices/heartbeat'
    | '/api/public/devices/signal/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LogsRoute: typeof LogsRoute
  RecordingsRoute: typeof RecordingsRoute
  SettingsRoute: typeof SettingsRoute
  TrafficLightIdRoute: typeof TrafficLightIdRoute
  ApiPublicDevicesDetectionRoute: typeof ApiPublicDevicesDetectionRoute
  ApiPublicDevicesHeartbeatRoute: typeof ApiPublicDevicesHeartbeatRoute
  ApiPublicDevicesSignalIdRoute: typeof ApiPublicDevicesSignalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic-light/$id': {
      id: '/traffic-light/$id'
      path: '/traffic-light/$id'
      fullPath: '/traffic-light/$id'
      preLoaderRoute: typeof TrafficLightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/heartbeat': {
      id: '/api/public/devices/heartbeat'
      path: '/api/public/devices/heartbeat'
      fullPath: '/api/public/devices/heartbeat'
      preLoaderRoute: typeof ApiPublicDevicesHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/detection': {
      id: '/api/public/devices/detection'
      path: '/api/public/devices/detection'
      fullPath: '/api/public/devices/detection'
      preLoaderRoute: typeof ApiPublicDevicesDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/devices/signal/$id': {
      id: '/api/public/devices/signal/$id'
      path: '/api/public/devices/signal/$id'
      fullPath: '/api/public/devices/signal/$id'
      preLoaderRoute: typeof ApiPublicDevicesSignalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LogsRoute: LogsRoute,
  RecordingsRoute: RecordingsRoute,
  SettingsRoute: SettingsRoute,
  TrafficLightIdRoute: TrafficLightIdRoute,
  ApiPublicDevicesDetectionRoute: ApiPublicDevicesDetectionRoute,
  ApiPublicDevicesHeartbeatRoute: ApiPublicDevicesHeartbeatRoute,
  ApiPublicDevicesSignalIdRoute: ApiPublicDevicesSignalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
